/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPerbendaharaanRouteImport } from './routes/_authenticated/perbendaharaan'
import { Route as AuthenticatedParaBangsawanRouteImport } from './routes/_authenticated/para-bangsawan'
import { Route as AuthenticatedForumRouteImport } from './routes/_authenticated/forum'
import { Route as AuthenticatedBankMateriRouteImport } from './routes/_authenticated/bank-materi'
import { Route as AuthenticatedBalaiTugasRouteImport } from './routes/_authenticated/balai-tugas'
import { Route as AuthenticatedBalaiKenanganRouteImport } from './routes/_authenticated/balai-kenangan'
import { Route as AuthenticatedAlmanakRouteImport } from './routes/_authenticated/almanak'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAbsenRouteImport } from './routes/_authenticated/absen'
import { Route as AuthenticatedForumTopikIdRouteImport } from './routes/_authenticated/forum.$topikId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerbendaharaanRoute =
  AuthenticatedPerbendaharaanRouteImport.update({
    id: '/perbendaharaan',
    path: '/perbendaharaan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParaBangsawanRoute =
  AuthenticatedParaBangsawanRouteImport.update({
    id: '/para-bangsawan',
    path: '/para-bangsawan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForumRoute = AuthenticatedForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankMateriRoute = AuthenticatedBankMateriRouteImport.update({
  id: '/bank-materi',
  path: '/bank-materi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBalaiTugasRoute = AuthenticatedBalaiTugasRouteImport.update({
  id: '/balai-tugas',
  path: '/balai-tugas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBalaiKenanganRoute =
  AuthenticatedBalaiKenanganRouteImport.update({
    id: '/balai-kenangan',
    path: '/balai-kenangan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlmanakRoute = AuthenticatedAlmanakRouteImport.update({
  id: '/almanak',
  path: '/almanak',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbsenRoute = AuthenticatedAbsenRouteImport.update({
  id: '/absen',
  path: '/absen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumTopikIdRoute =
  AuthenticatedForumTopikIdRouteImport.update({
    id: '/$topikId',
    path: '/$topikId',
    getParentRoute: () => AuthenticatedForumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/absen': typeof AuthenticatedAbsenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/almanak': typeof AuthenticatedAlmanakRoute
  '/balai-kenangan': typeof AuthenticatedBalaiKenanganRoute
  '/balai-tugas': typeof AuthenticatedBalaiTugasRoute
  '/bank-materi': typeof AuthenticatedBankMateriRoute
  '/forum': typeof AuthenticatedForumRouteWithChildren
  '/para-bangsawan': typeof AuthenticatedParaBangsawanRoute
  '/perbendaharaan': typeof AuthenticatedPerbendaharaanRoute
  '/forum/$topikId': typeof AuthenticatedForumTopikIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/absen': typeof AuthenticatedAbsenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/almanak': typeof AuthenticatedAlmanakRoute
  '/balai-kenangan': typeof AuthenticatedBalaiKenanganRoute
  '/balai-tugas': typeof AuthenticatedBalaiTugasRoute
  '/bank-materi': typeof AuthenticatedBankMateriRoute
  '/forum': typeof AuthenticatedForumRouteWithChildren
  '/para-bangsawan': typeof AuthenticatedParaBangsawanRoute
  '/perbendaharaan': typeof AuthenticatedPerbendaharaanRoute
  '/': typeof AuthenticatedIndexRoute
  '/forum/$topikId': typeof AuthenticatedForumTopikIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/absen': typeof AuthenticatedAbsenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/almanak': typeof AuthenticatedAlmanakRoute
  '/_authenticated/balai-kenangan': typeof AuthenticatedBalaiKenanganRoute
  '/_authenticated/balai-tugas': typeof AuthenticatedBalaiTugasRoute
  '/_authenticated/bank-materi': typeof AuthenticatedBankMateriRoute
  '/_authenticated/forum': typeof AuthenticatedForumRouteWithChildren
  '/_authenticated/para-bangsawan': typeof AuthenticatedParaBangsawanRoute
  '/_authenticated/perbendaharaan': typeof AuthenticatedPerbendaharaanRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/forum/$topikId': typeof AuthenticatedForumTopikIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/absen'
    | '/admin'
    | '/almanak'
    | '/balai-kenangan'
    | '/balai-tugas'
    | '/bank-materi'
    | '/forum'
    | '/para-bangsawan'
    | '/perbendaharaan'
    | '/forum/$topikId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/absen'
    | '/admin'
    | '/almanak'
    | '/balai-kenangan'
    | '/balai-tugas'
    | '/bank-materi'
    | '/forum'
    | '/para-bangsawan'
    | '/perbendaharaan'
    | '/'
    | '/forum/$topikId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/absen'
    | '/_authenticated/admin'
    | '/_authenticated/almanak'
    | '/_authenticated/balai-kenangan'
    | '/_authenticated/balai-tugas'
    | '/_authenticated/bank-materi'
    | '/_authenticated/forum'
    | '/_authenticated/para-bangsawan'
    | '/_authenticated/perbendaharaan'
    | '/_authenticated/'
    | '/_authenticated/forum/$topikId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perbendaharaan': {
      id: '/_authenticated/perbendaharaan'
      path: '/perbendaharaan'
      fullPath: '/perbendaharaan'
      preLoaderRoute: typeof AuthenticatedPerbendaharaanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/para-bangsawan': {
      id: '/_authenticated/para-bangsawan'
      path: '/para-bangsawan'
      fullPath: '/para-bangsawan'
      preLoaderRoute: typeof AuthenticatedParaBangsawanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum': {
      id: '/_authenticated/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof AuthenticatedForumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank-materi': {
      id: '/_authenticated/bank-materi'
      path: '/bank-materi'
      fullPath: '/bank-materi'
      preLoaderRoute: typeof AuthenticatedBankMateriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balai-tugas': {
      id: '/_authenticated/balai-tugas'
      path: '/balai-tugas'
      fullPath: '/balai-tugas'
      preLoaderRoute: typeof AuthenticatedBalaiTugasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balai-kenangan': {
      id: '/_authenticated/balai-kenangan'
      path: '/balai-kenangan'
      fullPath: '/balai-kenangan'
      preLoaderRoute: typeof AuthenticatedBalaiKenanganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/almanak': {
      id: '/_authenticated/almanak'
      path: '/almanak'
      fullPath: '/almanak'
      preLoaderRoute: typeof AuthenticatedAlmanakRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/absen': {
      id: '/_authenticated/absen'
      path: '/absen'
      fullPath: '/absen'
      preLoaderRoute: typeof AuthenticatedAbsenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/$topikId': {
      id: '/_authenticated/forum/$topikId'
      path: '/$topikId'
      fullPath: '/forum/$topikId'
      preLoaderRoute: typeof AuthenticatedForumTopikIdRouteImport
      parentRoute: typeof AuthenticatedForumRoute
    }
  }
}

interface AuthenticatedForumRouteChildren {
  AuthenticatedForumTopikIdRoute: typeof AuthenticatedForumTopikIdRoute
}

const AuthenticatedForumRouteChildren: AuthenticatedForumRouteChildren = {
  AuthenticatedForumTopikIdRoute: AuthenticatedForumTopikIdRoute,
}

const AuthenticatedForumRouteWithChildren =
  AuthenticatedForumRoute._addFileChildren(AuthenticatedForumRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbsenRoute: typeof AuthenticatedAbsenRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlmanakRoute: typeof AuthenticatedAlmanakRoute
  AuthenticatedBalaiKenanganRoute: typeof AuthenticatedBalaiKenanganRoute
  AuthenticatedBalaiTugasRoute: typeof AuthenticatedBalaiTugasRoute
  AuthenticatedBankMateriRoute: typeof AuthenticatedBankMateriRoute
  AuthenticatedForumRoute: typeof AuthenticatedForumRouteWithChildren
  AuthenticatedParaBangsawanRoute: typeof AuthenticatedParaBangsawanRoute
  AuthenticatedPerbendaharaanRoute: typeof AuthenticatedPerbendaharaanRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbsenRoute: AuthenticatedAbsenRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlmanakRoute: AuthenticatedAlmanakRoute,
  AuthenticatedBalaiKenanganRoute: AuthenticatedBalaiKenanganRoute,
  AuthenticatedBalaiTugasRoute: AuthenticatedBalaiTugasRoute,
  AuthenticatedBankMateriRoute: AuthenticatedBankMateriRoute,
  AuthenticatedForumRoute: AuthenticatedForumRouteWithChildren,
  AuthenticatedParaBangsawanRoute: AuthenticatedParaBangsawanRoute,
  AuthenticatedPerbendaharaanRoute: AuthenticatedPerbendaharaanRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
